apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k3d-ec2-operator.fullname" . }}-controller-manager
  labels:
  {{- include "k3d-ec2-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}